### PR TITLE
Made some small modification

### PR DESCRIPTION
**Pull request by akalcik**

### CODE REVIEW

**Comment by akalcik** [comment]
@kwaxi Actually as a student I would not be clear what is to do to implement. Can you maybe provide clear description what is to do?

**Comment by kwaxi** [comment]
I'll read through it again this your comment in mind. However, my idea was to create more challanging exercises were the description isn't so specific about the actual solution as in our scratch examples.

**Comment by akalcik** [comment]
I'm still not sure if it is enough.  Maybe you ask our mentors on Slack if they understand what to do is.

**Comment by akalcik** [comment]
Do not forget add this exercise to [exercise ](https://wien.coderdojo.net/exercises/)web page, when finished.

**Pull request closed without merging**
