### PR TITLE
Added selfie-bot

### PR DESCRIPTION
**Pull request by christian-vorhemus**

### CODE REVIEW

**Comment by akalcik** [comment]
@christian-vorhemus As I'm not experienced node.js developer please review my changes. I deleted obj, bin and node_modules folders as they normally are not checked into repository.

**Comment by christian-vorhemus** [comment]
True - I just thought for a starter project it's easier to deliver all necessary packages with the solution so it's really a click-and-run example. Will update the README because now "npm install" is necessary.

**Comment by akalcik** [comment]
@christian-vorhemus Can we merge it now? Runs the solution now?

**Comment by akalcik** [comment]
@christian-vorhemus  Houston we have a problem 

image

**Pull request merged**
